import type { Metadata } from "next";
import { Raleway  } from "next/font/google";
import "./globals.css";
import Footer from "./_componets/Footer";
import { Toaster } from "@/components/ui/sonner"

import { ThemeProvider } from "next-themes";
import Header from "./_componets/header";

const raleway = Raleway({
  
  subsets: ["latin"],
});


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="light" style={{ colorScheme: "light" }}>
  <body className={`${raleway.className} antialiased`}>
        <ThemeProvider attribute="class" defaultTheme="light" enableSystem>
          <div className="md:px-20">
            <Header />
            {children}
             <Toaster />
            <Footer />
          </div>
          
        </ThemeProvider>
      </body>
    </html>
  );
}
